routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WelcomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    Route::get('/home', function () {
        return view('backend.home');
    })->name('home');

    Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('roles/{role}', [RoleController::class, 'show'])->name('roles.show');

    // Category
    Route::get('categories/export/', [CategoryController::class, 'export'])->name('categories.export');
    Route::get('categories/pdf/', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');
    Route::get('/trashed-categories', [CategoryController::class, 'trash'])
        ->name('categories.trashed')->middleware('age_checker');
    Route::get('/trashed-categories/{category}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/trashed-categories/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);
   
    //Product
    Route::resource('products', ProductController::class);

     //Tags
     Route::resource('tags',TagController::class);
    
    // User
    Route::get('users/export/', [UserController::class, 'export'])->name('users.export');
    Route::get('users/pdf/', [UserController::class, 'downloadPdf'])->name('users.pdf');
    Route::get('/trashed-users', [UserController::class, 'trash'])
        ->name('users.trashed')->middleware('age_checker');
    Route::get('/trashed-users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('/trashed-users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');

    Route::get('/users/edit-profile', [ProfileController::class, 'edit'])->name('users.profile.edit');

    Route::patch('/users/update-profile', [ProfileController::class, 'update'])->name('users.profile.update');

    Route::resource('users', UserController::class)->except(
        ['create', 'store']
    );

});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Database\QueryException;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tagsCollection = Tag::latest();

        if (request('search')) {
            $tagsCollection = $tagsCollection
                ->where('name', 'like', '%' . request('search') . '%');
               
        }

        $tags = $tagsCollection->paginate(10);

        return view('backend.tags.index', [
            'tags' => $tags
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy('name', 'asc')
        ->pluck('name', 'id')
        ->toArray();

       $categories = Category::orderBy('title', 'asc')
        ->pluck('title', 'id')
        ->toArray();

        return view('backend.tags.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $product = Tag::create([
                // 'category_id' => $request->category_id,
                'name' => $request->title,
               
            ]);

           // $product->tags()->attach($request->tag_id);

            return redirect()->route('tags.index')->withMessage('Successfully Created!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
         
         return view('backend.tags.show', [
            'tag' => $tag
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('backend.tags.edit', [
            'tag' => $tag
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
      
        try {
            $requestData = [
               
                'name' => $request->name,
                
            ];

            $tag->update($requestData);

            return redirect()->route('tags.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        try {
            $tag->delete();
            return redirect()->route('tags.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/backend/tags/create.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Add Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Tags </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Create Product <a class="btn btn-sm btn-info" href="{{ route('tags.index') }}">List</a>
        </div>
        <div class="card-body">

            <x-backend.layouts.elements.errors :errors="$errors" />

            <form action="{{ route('tags.store') }}" enctype="multipart/form-data" method="post">
                @csrf

                <x-backend.form.field>
                    <!-- <select name="category_id" id="category_id" class="form-select">
                        @foreach ($categories as $key=>$value)
                        <option value="{{ $key }}">{{ $value }}</option>
                        @endforeach
                    </select>
                    <x-backend.form.error name="category_id" /> -->
                </x-backend.form.field>

                <x-backend.form.input name="title" />

                <!-- <x-backend.form.textarea name="description" />

                <x-backend.form.input name="image" type="file" /> -->


                @foreach ($tags as $key=>$value)
                <input type="checkbox" name="tag_id[]" value="{{ $key }}"> {{ $value }}
                @endforeach

                <br/>

                <x-backend.form.button>Save</x-backend.form.button>
            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/tags/edit.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Edit Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Tags </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Edit Tags <a class="btn btn-sm btn-info" href="{{ route('tags.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('tags.update', ['tag' => $tag->id]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')

                <x-backend.form.input name="name" :value="$tag->name" />
               
                <x-backend.form.button>Update</x-backend.form.button>

            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/tags/index.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Tags
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Tags </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Tags</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Products


            <a class="btn btn-sm btn-info" href="{{ route('tags.create') }}">Add New</a>

        </div>
        <div class="card-body">

            <x-backend.layouts.elements.message :message="session('message')" />

            <form method="GET" action="{{ route('tags.index') }}">
                <x-backend.form.input style="width: 200px;" name='search' />

            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($tags as $tag)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $tag->name }}</td>
                        
                        <td>
                            <a class="btn btn-info btn-sm" href="{{ route('tags.show', ['tag' => $tag->id]) }}">Show</a>

                            <a class="btn btn-warning btn-sm" href="{{ route('tags.edit', ['tag' => $tag->id]) }}">Edit</a>

                            <form style="display:inline" action="{{ route('tags.destroy', ['tag' => $tag->id]) }}" method="post">
                                @csrf
                                @method('delete')

                                <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>

                         


                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
            {{ $tags->links() }}
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/tags/pdf.blade.php
<table id="datatablesSimple" border="1">
    <thead>
        <tr>
            <th>Sl#</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    @php $sl=0 @endphp
        @foreach ($categories as $category)
        <tr>
            <td>{{ ++$sl }}</td>
            <td>{{ $category->title }}</td>
            <td>{{ $category->description }}</td>
            
        </tr>
        @endforeach

    </tbody>
</table>

resources/views/backend/tags/show.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Details
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Tags </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Category Details <a class="btn btn-sm btn-info" href="{{ route('tags.index') }}">List</a>
        </div>
        <div class="card-body">
            <h3>Title: {{ $tag->name }}</h3>
            
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/tags/trashed.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Categories
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Categories</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Categories <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if (session('message'))
            <div class="alert alert-success">
                <span class="close" data-dismiss="alert">&times;</span>
                <strong>{{ session('message') }}.</strong>
            </div>
            @endif

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->description }}</td>
                        <td>
                        
                            <a class="btn btn-warning btn-sm" href="{{ route('categories.restore', ['category' => $category->id]) }}" >Restore</a>

                            <form style="display:inline" action="{{ route('categories.delete', ['category' => $category->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                <button onclick="return confirm('Are you sure want to delete permanently?')" class="btn btn-sm btn-danger" type="submit">Permanent Delete</button>
                            </form>

                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>

</x-backend.layouts.master>